"""Text extraction for Office documents and plain text (server/src/ingest/office.js).

Word, Excel and PowerPoint are all a ZIP of XML parts (OOXML), so they share
one reader built on the standard library's zipfile. Each extractor returns
numbered ``sections`` that chunk exactly like PDF pages, so "slide 12" works
the way "page 12" does.

XML is read with regular expressions rather than a parser. That works because
these parts are machine-generated by Office and only the text runs are pulled
out — no attributes to resolve, no namespaces to honour, no structure to
rebuild. A real XML parser is the right call the moment that stops being true.
"""

import datetime as dt
import io
import re
import zipfile

from ..utils.js import is_integer, js_trim, parse_float, parse_int
from .errors import INGEST_ERROR_CODES, IngestError

FREE_SECTION_LIMIT = 50

PLAIN_TEXT_MIME_TYPES = {"text/plain", "text/markdown", "text/csv"}

# `unit` is the word a student sees for a numbered part; "page 4" of a
# spreadsheet means nothing. `limitUnit` is the plural for the limit message.
OFFICE_FORMATS = {
    "docx": {"mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
             "label": "Word document", "unit": "section", "limitUnit": "sections"},
    "xlsx": {"mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
             "label": "Excel spreadsheet", "unit": "sheet", "limitUnit": "sheets"},
    "pptx": {"mimeType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
             "label": "PowerPoint presentation", "unit": "slide", "limitUnit": "slides"},
    "text": {"mimeType": "text/plain", "label": "Text file", "unit": "section", "limitUnit": "sections"},
}

_PREFIX = r"(?:[a-zA-Z0-9]+:)?"

# ---------------------------------------------------------------------------
# XML helpers
# ---------------------------------------------------------------------------


def _decode_entities(text):
    """The five predefined entities plus numeric references; &amp; LAST so &amp;lt; stays "&lt;"."""
    text = str(text).replace("&lt;", "<").replace("&gt;", ">").replace("&quot;", '"').replace("&apos;", "'")
    text = re.sub(r"&#x([0-9a-fA-F]+);", lambda m: chr(int(m.group(1), 16)), text)
    text = re.sub(r"&#(\d+);", lambda m: chr(int(m.group(1), 10)), text)
    return text.replace("&amp;", "&")


def _text_runs(xml, tag):
    """The text of every <tag>...</tag>, with an optional namespace prefix, in document order."""
    pattern = re.compile(rf"<{_PREFIX}{tag}(?:\s[^>]*)?>([\s\S]*?)</{_PREFIX}{tag}>")
    return [_decode_entities(match.group(1)) for match in pattern.finditer(xml)]


def _elements(xml, tag):
    """The elements named ``tag``, markup included."""
    pattern = re.compile(rf"<{_PREFIX}{tag}(?:\s[^>]*)?>[\s\S]*?</{_PREFIX}{tag}>")
    return [match.group(0) for match in pattern.finditer(xml)]


def _attribute(element, name):
    match = re.search(rf'\s{re.escape(name)}="([^"]*)"', element)
    return match.group(1) if match else None


def _text_of(zip_files, path):
    data = zip_files.get(path)
    return data.decode("utf-8", errors="replace") if data is not None else None


def _collapse(value):
    return js_trim(re.sub(r"\s+", " ", value))


# ---------------------------------------------------------------------------
# Word
# ---------------------------------------------------------------------------


def _extract_docx(zip_files, paragraphs_per_section=40):
    """Word has no pages, so it is divided into numbered SECTIONS of ~40 paragraphs."""
    xml = _text_of(zip_files, "word/document.xml")
    if xml is None:
        raise IngestError(INGEST_ERROR_CODES["EXTRACT_FAILED"],
                          "This Word file is missing its document body and may be corrupt.")

    paragraphs = []
    for paragraph in _elements(xml, "p"):
        runs = _text_runs(paragraph, "t")
        if not runs:
            continue
        line = _collapse("".join(runs))
        if line:
            paragraphs.append(line)

    sections = []
    for start in range(0, len(paragraphs), paragraphs_per_section):
        body = js_trim("\n".join(paragraphs[start:start + paragraphs_per_section]))
        if body:
            sections.append({"number": len(sections) + 1, "title": None, "text": body})
    return sections


# ---------------------------------------------------------------------------
# Excel
# ---------------------------------------------------------------------------


def _shared_strings(zip_files):
    xml = _text_of(zip_files, "xl/sharedStrings.xml")
    if not xml:
        return []
    # One <si> may hold several formatted <t> runs; they are one string.
    return ["".join(_text_runs(si, "t")) for si in _elements(xml, "si")]


BUILTIN_DATE_FORMATS = {14, 15, 16, 17, 18, 19, 20, 21, 22, 45, 46, 47}


def _date_format_ids(zip_files):
    """Style indices whose number format is a date (built-in ids or custom date tokens)."""
    xml = _text_of(zip_files, "xl/styles.xml")
    if not xml:
        return set()

    custom = set()
    for num_fmts in _elements(xml, "numFmts"):
        for fmt in re.findall(rf"<{_PREFIX}numFmt\s[^>]*/>", num_fmts):
            fmt_id = parse_int(_attribute(fmt, "numFmtId") or "")
            code = _attribute(fmt, "formatCode") or ""
            # Strip quoted literals so the "m" in a label like "Month" does not count.
            without_literals = re.sub(r'"[^"]*"', "", code)
            if re.search(r"[dmyhs]", without_literals, re.IGNORECASE) and not re.fullmatch(r"[#0.,%\s]*", without_literals):
                custom.add(fmt_id)

    cell_xfs = (_elements(xml, "cellXfs") or [""])[0]
    styles = [parse_int(_attribute(xf, "numFmtId") or "0") for xf in re.findall(rf"<{_PREFIX}xf\s[^>]*/?>", cell_xfs)]
    return {index for index, fmt_id in enumerate(styles) if fmt_id in BUILTIN_DATE_FORMATS or fmt_id in custom}


# Excel's day 0 is 1899-12-30 (it absorbs Lotus 1-2-3's leap-year bug).
EXCEL_EPOCH_MS = -2209161600000
_UNIX_EPOCH = dt.datetime(1970, 1, 1, tzinfo=dt.timezone.utc)


def _serial_to_date(serial):
    if serial != serial:  # NaN
        return "NaN"
    try:
        ms = int(EXCEL_EPOCH_MS + serial * 86_400_000)  # Date truncates towards zero
        value = _UNIX_EPOCH + dt.timedelta(milliseconds=ms)
    except (OverflowError, ValueError):
        return str(serial)
    iso = f"{value:%Y-%m-%dT%H:%M}"
    # A whole number is a date; a fraction carries a time of day worth keeping.
    return iso[:10] if is_integer(serial) else iso.replace("T", " ")


def _column_of(reference):
    match = re.match(r"^([A-Z]+)", reference or "")
    return match.group(1) if match else ""


def _row_of(reference):
    match = re.search(r"(\d+)$", reference or "")
    return int(match.group(1)) if match else 0


def _extract_sheet(xml, strings, date_styles):
    """One sheet becomes tab-separated lines — tabs, because cell values contain commas."""
    lines = []
    cell_pattern = re.compile(rf"<{_PREFIX}c(?:\s[^>]*)?(?:/>|>[\s\S]*?</{_PREFIX}c>)")
    for row in _elements(xml, "row"):
        cells = []
        for cell in cell_pattern.findall(row):
            kind = _attribute(cell, "t")
            style_index = parse_int(_attribute(cell, "s") or "")
            reference = _attribute(cell, "r")

            if kind == "s":
                index = parse_int((_text_runs(cell, "v") or [""])[0])
                value = strings[index] if index is not None and 0 <= index < len(strings) else ""
            elif kind == "inlineStr":
                value = "".join(_text_runs(cell, "t"))
            elif kind == "str":
                value = (_text_runs(cell, "v") or [""])[0]
            elif kind == "b":
                value = "TRUE" if (_text_runs(cell, "v") or [None])[0] == "1" else "FALSE"
            else:
                runs = _text_runs(cell, "v")
                if not runs:
                    value = ""
                elif style_index is not None and style_index in date_styles and runs[0] != "":
                    value = _serial_to_date(parse_float(runs[0]))
                else:
                    value = runs[0]

            if value != "":
                cells.append({"column": _column_of(reference), "value": _collapse(str(value))})

        if cells:
            lines.append({"row": _row_of(_attribute(row, "r")), "text": "\t".join(c["value"] for c in cells)})

    return "\n".join(line["text"] for line in lines if line["text"].strip())


def _extract_xlsx(zip_files):
    """Sheet order comes from workbook.xml and its relationships, never from file names."""
    workbook = _text_of(zip_files, "xl/workbook.xml")
    if workbook is None:
        raise IngestError(INGEST_ERROR_CODES["EXTRACT_FAILED"],
                          "This Excel file is missing its workbook and may be corrupt.")

    strings = _shared_strings(zip_files)
    date_styles = _date_format_ids(zip_files)

    rels_xml = _text_of(zip_files, "xl/_rels/workbook.xml.rels") or ""
    relationships = {}
    for rel in re.findall(r"<Relationship\s[^>]*/?>", rels_xml):
        rel_id, target = _attribute(rel, "Id"), _attribute(rel, "Target")
        if rel_id and target:
            relationships[rel_id] = re.sub(r"^/", "", re.sub(r"^/?xl/", "", target))

    sections = []
    for index, sheet in enumerate(re.findall(rf"<{_PREFIX}sheet\s[^>]*/?>", workbook)):
        name = _attribute(sheet, "name") or f"Sheet{index + 1}"
        rel_id = _attribute(sheet, "r:id") or _attribute(sheet, "id")
        target = relationships.get(rel_id) if rel_id else None
        sheet_xml = _text_of(zip_files, f"xl/{target or f'worksheets/sheet{index + 1}.xml'}")
        if sheet_xml is None:
            continue
        body = _extract_sheet(sheet_xml, strings, date_styles)
        if body.strip():
            # Numbered by position in the workbook, so an empty sheet never renumbers the rest.
            sections.append({"number": index + 1, "title": name, "text": f"{name}\n{body}"})
    return sections


# ---------------------------------------------------------------------------
# PowerPoint
# ---------------------------------------------------------------------------


def _slide_paths(zip_files):
    """Slide order from the presentation's relationships; numeric file order as a fallback."""
    presentation = _text_of(zip_files, "ppt/presentation.xml")
    rels_xml = _text_of(zip_files, "ppt/_rels/presentation.xml.rels")

    if presentation and rels_xml:
        relationships = {}
        for rel in re.findall(r"<Relationship\s[^>]*/?>", rels_xml):
            rel_id, target = _attribute(rel, "Id"), _attribute(rel, "Target")
            if rel_id and target:
                relationships[rel_id] = re.sub(r"^/", "", re.sub(r"^\.\./", "", target))
        ordered = []
        for sld_id in re.findall(rf"<{_PREFIX}sldId\s[^>]*/?>", presentation):
            rel_id = _attribute(sld_id, "r:id") or _attribute(sld_id, "id")
            target = relationships.get(rel_id) if rel_id else None
            if target:
                ordered.append(target if target.startswith("ppt/") else f"ppt/{target}")
        if ordered:
            return ordered

    paths = [path for path in zip_files if re.fullmatch(r"ppt/slides/slide\d+\.xml", path)]
    return sorted(paths, key=lambda path: int(re.search(r"(\d+)\.xml$", path).group(1)))


def _notes_for(zip_files, slide_path):
    """Speaker notes through the slide's own relationships — never by matching numbers."""
    name = slide_path.split("/")[-1]
    rels_xml = _text_of(zip_files, f"ppt/slides/_rels/{name}.rels")
    if not rels_xml:
        return None
    for rel in re.findall(r"<Relationship\s[^>]*/?>", rels_xml):
        if not re.search(r"notesSlide$", _attribute(rel, "Type") or ""):
            continue
        target = _attribute(rel, "Target")
        if not target:
            continue
        path = re.sub(r"^/", "", re.sub(r"^\.\./", "ppt/", target))
        return _text_of(zip_files, path if path.startswith("ppt/") else f"ppt/slides/{path}")
    return None


def _extract_pptx(zip_files):
    sections = []
    for index, path in enumerate(_slide_paths(zip_files)):
        xml = _text_of(zip_files, path)
        if xml is None:
            continue
        lines = [line for line in (_collapse("".join(_text_runs(p, "t"))) for p in _elements(xml, "p")) if line]

        slide_number = index + 1
        notes_xml = _notes_for(zip_files, path)
        notes = []
        if notes_xml:
            notes = [line for line in (_collapse("".join(_text_runs(p, "t"))) for p in _elements(notes_xml, "p"))
                     # PowerPoint puts the slide number itself in the notes placeholder.
                     if line and line != str(slide_number)]

        body = js_trim("\n".join(part for part in [
            "\n".join(lines),
            f"Speaker notes: {' '.join(notes)}" if notes else "",
        ] if part))

        if body:
            # Numbered by POSITION IN THE DECK: a picture-only slide must not shift the rest.
            sections.append({"number": slide_number, "title": lines[0] if lines else None, "text": body})
    return sections


# ---------------------------------------------------------------------------
# Plain text
# ---------------------------------------------------------------------------


def _extract_plain_text(data):
    """Plain text is one section; there are no numbered parts to cite."""
    text = js_trim(data.decode("utf-8", errors="replace").replace("\r\n", "\n"))
    return [{"number": 1, "title": None, "text": text}] if text else []


# ---------------------------------------------------------------------------
# Format detection and entry point
# ---------------------------------------------------------------------------


def detect_ooxml_format(zip_files):
    """Identifies an OOXML package by what is inside it rather than by its name."""
    if "word/document.xml" in zip_files:
        return "docx"
    if "xl/workbook.xml" in zip_files:
        return "xlsx"
    if "ppt/presentation.xml" in zip_files:
        return "pptx"
    return None


def format_for_mime_type(mime_type):
    if mime_type in PLAIN_TEXT_MIME_TYPES:
        return "text"
    return next((key for key, fmt in OFFICE_FORMATS.items() if fmt["mimeType"] == mime_type), None)


def _unzip(data):
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        return {info.filename: archive.read(info) for info in archive.infolist() if not info.is_dir()}


def extract_document(source, mime_type=None, plan_tier="free"):
    """Extracts a document from a path or bytes into numbered sections plus full text."""
    if isinstance(source, (bytes, bytearray)):
        data = bytes(source)
    else:
        with open(source, "rb") as handle:
            data = handle.read()

    if len(data) == 0:
        raise IngestError(INGEST_ERROR_CODES["EXTRACT_FAILED"], "This file is empty. Please upload it again.")

    claimed = format_for_mime_type(mime_type)
    fmt = claimed
    if claimed == "text":
        sections = _extract_plain_text(data)
    else:
        try:
            zip_files = _unzip(data)
        except Exception as err:
            raise IngestError(
                INGEST_ERROR_CODES["EXTRACT_FAILED"],
                f"This file could not be opened — it may be corrupt or password-protected ({err}).",
            ) from err

        # What the package actually is beats what the upload claimed.
        fmt = detect_ooxml_format(zip_files)
        if not fmt:
            raise IngestError(INGEST_ERROR_CODES["EXTRACT_FAILED"],
                              "This does not look like a Word, Excel or PowerPoint file.")
        sections = {"docx": _extract_docx, "xlsx": _extract_xlsx, "pptx": _extract_pptx}[fmt](zip_files)

    info = OFFICE_FORMATS[fmt]
    if not sections:
        raise IngestError(INGEST_ERROR_CODES["EMPTY_CONTENT"],
                          f"No readable text could be found in this {info['label'].lower()}.")

    # Charged against the same free-plan allowance a PDF's pages are, checked
    # after extraction because these formats do not record a part count.
    if plan_tier != "plus" and len(sections) > FREE_SECTION_LIMIT:
        raise IngestError(
            INGEST_ERROR_CODES["PAGE_LIMIT_EXCEEDED"],
            f"Free plan allows up to {FREE_SECTION_LIMIT} {info['limitUnit']} per document "
            f"(this one has {len(sections)}). Please upgrade to Plus for larger documents.",
            {"sectionCount": len(sections), "limit": FREE_SECTION_LIMIT, "unit": info["unit"]},
        )

    full_text = js_trim("\n\n".join(section["text"] for section in sections))
    if not full_text:
        raise IngestError(INGEST_ERROR_CODES["EMPTY_CONTENT"],
                          f"No readable text could be found in this {info['label'].lower()}.")

    return {"format": fmt, "label": info["label"], "unit": info["unit"], "sectionCount": len(sections),
            "sections": sections, "fullText": full_text}
