"""SQL for quizzes, questions and attempts (server/src/db/quiz.db.js)."""

from ..extensions import query, query_one, transaction
from ..utils.js import js_string
from ..utils.serialization import dumps

QUIZ_SELECT = """
  SELECT q.id, q.study_kit_id, q.source_id, q.title, q.language, q.difficulty,
         q.question_count, q.status, q.created_at"""


def _upsert_topic(tx, study_kit_id, name):
    return tx.query_one(
        """INSERT INTO topics (study_kit_id, name) VALUES ($1, $2)
           ON CONFLICT (study_kit_id, name) WHERE study_kit_id IS NOT NULL
           DO UPDATE SET name = EXCLUDED.name RETURNING id""",
        [study_kit_id, name],
    )


def save_generated(*, cache_id, source, quiz, params, model):
    with transaction() as tx:
        inserted = tx.query_one(
            """INSERT INTO quizzes
                 (study_kit_id, source_id, generation_cache_id, title, language, difficulty,
                  question_count, generated_by_ai, status, description)
               VALUES ($1, $2, $3, $4, $5, $6, $7, true, 'ready', $8)
               ON CONFLICT (generation_cache_id) WHERE generation_cache_id IS NOT NULL
               DO UPDATE SET title = EXCLUDED.title
               RETURNING id""",
            [source["study_kit_id"], source["id"], cache_id, quiz["title"], params["language"],
             params["difficulty"], len(quiz["questions"]), f"Generated by {model}"],
        )
        for position, question in enumerate(quiz["questions"]):
            topic = _upsert_topic(tx, source["study_kit_id"], question["topic"]) if question.get("topic") else None
            tx.query(
                """INSERT INTO quiz_questions
                     (quiz_id, position, kind, prompt, options, correct_answer, explanation,
                      topic_label, topic_id, targeted_weak_concept)
                   VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
                   ON CONFLICT (quiz_id, position) DO NOTHING""",
                [inserted["id"], position, question["kind"], question["prompt"], dumps(question["options"]),
                 dumps(question["correctAnswer"]), question["explanation"], question.get("topic"),
                 topic["id"] if topic else None, question.get("targetedWeakConcept")],
            )
        tx.query("UPDATE ai_generation_cache SET status = 'ready', error_message = NULL WHERE id = $1", [cache_id])
        return inserted


def seen_questions(*, user_id, source_id, limit=60):
    """Prompts this student has actually answered on this material, newest first."""
    rows = query(
        """SELECT DISTINCT ON (qq.id) qq.prompt, a.answered_at
             FROM quiz_attempt_answers a
             JOIN quiz_attempts att ON att.id = a.attempt_id
             JOIN quiz_questions qq ON qq.id = a.question_id
             JOIN quizzes q ON q.id = qq.quiz_id
            WHERE att.user_id = $1 AND q.source_id = $2
            ORDER BY qq.id, a.answered_at DESC""",
        [user_id, source_id],
    ).rows
    rows.sort(key=lambda row: row["answered_at"], reverse=True)
    return [row["prompt"] for row in rows[:limit]]


def weak_topics(*, user_id, source_id, limit=6):
    """What this student keeps getting wrong on this material, worst first."""
    return query(
        """SELECT qq.topic_label AS topic,
                  count(*) FILTER (WHERE a.is_correct IS FALSE)::int AS wrong,
                  count(*)::int AS asked,
                  COALESCE(min(m.mastery_percent), 100)::int AS mastery
             FROM quiz_attempt_answers a
             JOIN quiz_attempts att ON att.id = a.attempt_id
             JOIN quiz_questions qq ON qq.id = a.question_id
             JOIN quizzes q ON q.id = qq.quiz_id
             LEFT JOIN user_topic_mastery m ON m.topic_id = qq.topic_id AND m.user_id = $1
            WHERE att.user_id = $1 AND q.source_id = $2
              AND qq.topic_label IS NOT NULL AND qq.topic_label <> ''
            GROUP BY qq.topic_label
           HAVING count(*) FILTER (WHERE a.is_correct IS FALSE) > 0
            ORDER BY (count(*) FILTER (WHERE a.is_correct IS FALSE))::float / count(*) DESC,
                     min(m.mastery_percent) ASC NULLS LAST
            LIMIT $3""",
        [user_id, source_id, limit],
    ).rows


def completed_rounds(*, user_id, source_id):
    """How many quizzes on this material the student has finished — the cache-key round."""
    row = query_one(
        """SELECT count(DISTINCT att.id)::int AS rounds
             FROM quiz_attempts att
             JOIN quizzes q ON q.id = att.quiz_id
            WHERE att.user_id = $1 AND q.source_id = $2 AND att.status = 'submitted'""",
        [user_id, source_id],
    )
    return row["rounds"] if row else 0


def by_cache(cache_id):
    return query_one(f"{QUIZ_SELECT} FROM quizzes q WHERE q.generation_cache_id = $1", [cache_id])


def questions(quiz_id, answers_for_attempt_id=None):
    return query(
        """SELECT qq.id, qq.position, qq.kind, qq.prompt, qq.options, qq.explanation,
                  qq.topic_label, qq.targeted_weak_concept, a.response, a.is_correct, a.answered_at,
                  CASE WHEN a.id IS NULL THEN NULL ELSE qq.correct_answer END AS revealed_answer
             FROM quiz_questions qq
             LEFT JOIN quiz_attempt_answers a
               ON a.question_id = qq.id AND a.attempt_id = $2
            WHERE qq.quiz_id = $1 ORDER BY qq.position""",
        [quiz_id, answers_for_attempt_id],
    ).rows


def start_attempt(*, user_id, quiz_id):
    with transaction() as tx:
        quiz = tx.query_one(
            """SELECT q.id, q.question_count FROM quizzes q
               JOIN study_kits k ON k.id = q.study_kit_id
               WHERE q.id = $1 AND k.user_id = $2 AND q.status = 'ready'""",
            [quiz_id, user_id],
        )
        if not quiz:
            return None
        return tx.query_one(
            "INSERT INTO quiz_attempts (quiz_id, user_id, total_questions) VALUES ($1, $2, $3) RETURNING *",
            [quiz_id, user_id, quiz["question_count"]],
        )


def attempt(*, user_id, attempt_id):
    return query_one(
        """SELECT a.*, q.title AS quiz_title, q.study_kit_id, q.language
             FROM quiz_attempts a JOIN quizzes q ON q.id = a.quiz_id
            WHERE a.id = $1 AND a.user_id = $2""",
        [attempt_id, user_id],
    )


def is_correct_answer(expected, response):
    """String answers compare trimmed and case-folded; indices compare exactly."""
    if isinstance(expected, str):
        return js_string(response).strip().lower() == expected.strip().lower()
    if isinstance(response, bool) or isinstance(expected, bool):
        return response is expected
    return response == expected


def save_answer(*, user_id, attempt_id, question_id, response, time_spent_seconds=None):
    with transaction() as tx:
        row = tx.query_one(
            """SELECT a.id, a.status, qq.correct_answer, qq.kind
                 FROM quiz_attempts a JOIN quiz_questions qq ON qq.quiz_id = a.quiz_id
                WHERE a.id = $1 AND a.user_id = $2 AND qq.id = $3 FOR UPDATE""",
            [attempt_id, user_id, question_id],
        )
        if not row or row["status"] != "in_progress":
            return None
        correct = is_correct_answer(row["correct_answer"], response)
        return tx.query_one(
            """INSERT INTO quiz_attempt_answers
                 (attempt_id, question_id, response, is_correct, time_spent_seconds)
               VALUES ($1, $2, $3, $4, $5)
               ON CONFLICT (attempt_id, question_id) DO UPDATE
                 SET response = EXCLUDED.response, is_correct = EXCLUDED.is_correct,
                     time_spent_seconds = EXCLUDED.time_spent_seconds, answered_at = now()
               RETURNING response, is_correct, answered_at""",
            [attempt_id, question_id, dumps(response), correct, time_spent_seconds],
        )


def submit_stats(*, user_id, attempt_id):
    with transaction() as tx:
        current = tx.query_one(
            """SELECT a.*, q.title AS quiz_title, q.language FROM quiz_attempts a
               JOIN quizzes q ON q.id = a.quiz_id
               WHERE a.id = $1 AND a.user_id = $2 FOR UPDATE""",
            [attempt_id, user_id],
        )
        if not current or current["status"] != "in_progress":
            return current
        stats = tx.query_one(
            """SELECT count(*) FILTER (WHERE is_correct)::int AS correct,
                      array_remove(array_agg(qq.topic_label) FILTER (WHERE NOT a.is_correct), NULL) AS missed_topics
                 FROM quiz_attempt_answers a JOIN quiz_questions qq ON qq.id = a.question_id
                WHERE a.attempt_id = $1""",
            [attempt_id],
        )
        return {**current, "computedCorrect": stats["correct"] or 0, "missedTopics": stats["missed_topics"] or []}


def finish_attempt(*, user_id, attempt_id, correct, mastery, takeaways):
    return query_one(
        """UPDATE quiz_attempts SET status = 'submitted', correct_count = $3,
                  mastery_percent = $4, takeaways = $5, submitted_at = now()
            WHERE id = $1 AND user_id = $2 AND status = 'in_progress' RETURNING *""",
        [attempt_id, user_id, correct, mastery, dumps(takeaways)],
    )
