-- Make the AI provider part of a cached generation's identity.
--
-- `ai_generation_cache` keyed a row by (source_id, method, params_hash) and
-- nothing else, so it could not tell content written by the mock provider from
-- content written by the real one. The consequence was not theoretical: every
-- source ingested before OPENAI_API_KEY was set holds mock output at
-- status 'ready', and `quizService.generate` returns early on a ready cache —
-- so a student kept being asked the mock's three canned database questions
-- about a document that had nothing to do with databases, permanently, with a
-- live key sitting right there.
--
-- With `provider` in the key, the same request under a different provider is a
-- different row. Mock content is missed rather than served, and regenerates on
-- demand. Nothing has to be invalidated by hand.
--
-- DEFAULT 'mock' is the correct backfill and not a guess: every row that exists
-- when this migration runs WAS written by the mock provider, because the key was
-- only ever set up on a database whose content predates the key.

ALTER TABLE ai_generation_cache
  ADD COLUMN provider text NOT NULL DEFAULT 'mock';

-- Mirrors PROVIDER_NAMES in server/src/ai/types.js. A provider added there
-- needs a migration here, which is deliberate: the cache is on disk and cannot
-- learn a new name from a code change alone.
ALTER TABLE ai_generation_cache
  ADD CONSTRAINT ai_generation_cache_provider_check
  CHECK (provider IN ('mock', 'openai'));

-- The old uniqueness is what let one provider's output occupy the other's slot.
--
-- Found by its definition rather than by name. 003 declared it inline as
-- `UNIQUE (source_id, method, params_hash)`, so its name was generated by
-- Postgres and is not written down anywhere in this repo. Naming it here would
-- be a guess, and a guess that is wrong fails this migration for a reason that
-- has nothing to do with what it is trying to do. RAISE makes a genuinely
-- missing constraint loud — this looks it up, it does not skip it.
DO $$
DECLARE
  old_name text;
BEGIN
  SELECT conname INTO old_name
    FROM pg_constraint
   WHERE conrelid = 'ai_generation_cache'::regclass
     AND contype = 'u'
     AND pg_get_constraintdef(oid) = 'UNIQUE (source_id, method, params_hash)';

  IF old_name IS NULL THEN
    RAISE EXCEPTION
      'ai_generation_cache has no UNIQUE (source_id, method, params_hash) to replace';
  END IF;

  EXECUTE format('ALTER TABLE ai_generation_cache DROP CONSTRAINT %I', old_name);
END $$;

ALTER TABLE ai_generation_cache
  ADD CONSTRAINT ai_generation_cache_source_method_params_provider_key
  UNIQUE (source_id, method, params_hash, provider);
